In [53]:
import numpy as np

## 1. MAE 와 RMSE 함수 구현하기
- 다음과 같이 실제 값과 , 모델이 예측한 값이 각각 100개가 있다.
- 실제값과 예측값 사이에 평균 오차를 구하는 함수 두개를 구현해보자.

In [54]:
np.random.seed(42) 
target = np.random.randint(50, 91,100) # 정답값
pred = np.random.randint(40, 100,100) # 예측값
target , pred

(array([88, 78, 64, 57, 70, 88, 68, 72, 60, 60, 73, 85, 89, 73, 52, 71, 51,
        73, 79, 87, 51, 70, 82, 61, 71, 74, 76, 77, 65, 64, 52, 86, 56, 70,
        58, 88, 67, 53, 74, 63, 58, 75, 51, 69, 77, 56, 57, 84, 63, 66, 85,
        89, 53, 51, 55, 53, 78, 67, 75, 83, 59, 85, 63, 80, 64, 57, 63, 72,
        89, 70, 65, 67, 73, 75, 74, 90, 78, 64, 50, 74, 56, 58, 73, 50, 57,
        73, 60, 66, 57, 84, 84, 82, 54, 88, 90, 77, 56, 58, 57, 61]),
 array([73, 72, 87, 94, 62, 63, 76, 74, 83, 79, 61, 66, 74, 40, 74, 76, 86,
        53, 42, 40, 44, 65, 94, 53, 78, 66, 48, 54, 54, 65, 81, 99, 52, 90,
        71, 78, 88, 91, 71, 43, 69, 76, 62, 78, 84, 54, 82, 68, 75, 52, 71,
        46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83, 59, 69,
        50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42, 78, 45,
        47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71, 63]))

### MAE(Mean Absolute Error)
- 실제 값과 예측 값의 차이를 절대값으로 변환해 평균화
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [55]:
def mae(target,pred):
    return np.abs(np.subtract(pred,target)).mean()
mae(target,pred)

17.8

### RMSE(Root Mean Squared Error)
- 실제 값과 예측 값의 차이를 제곱한 뒤 평균화한 후에 루트

$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [56]:
def rmse(target,pred):
    return np.sqrt(((pred - target) ** 2).mean())
rmse(target,pred)

21.829796151132516

## 2.시그모이드 함수 구현하기
- S와 같은 형태로 미분 가능한 0~1 사이의 값을 반환한다.
- 이진 분류에 출력 함수로 사용된다.
$$
y = \frac{1}{1+e^{-x}}
$$

- x 변수에 있는 배열의 요소들을 시그모이드 함수에 넣어 0 ~ 1 사이 값들로 변경하시오.

In [57]:
np.random.seed(42)
x = np.random.randint(-10,10,10)
x

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7])

```
아래 셀의 코드 작성하여 함수구현
```

In [58]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
sigmoid(x)

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

## 3.다음의 3행 2열형태의 배열에서 두개 열 위치를 바꾸시오.

In [59]:
np.random.seed(42)
arr = np.random.randint(50,100,[3,2])
arr

array([[88, 78],
       [64, 92],
       [57, 70]])

```
아래 셀의 코드 작성
```

In [60]:
np.fliplr(arr)

array([[78, 88],
       [92, 64],
       [70, 57]])

- 강사님 코드

In [61]:
arr[:,[1,0]]

array([[78, 88],
       [92, 64],
       [70, 57]])

## 4.다음의 배열에서 각행의 평균을 구하시오.

In [62]:
np.random.seed(42) 
arr = np.random.randint(50, 101, (4, 3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]])

```
아래 셀의 코드 작성
```

In [63]:
arr.mean(axis=1)

array([76.66666667, 73.        , 76.        , 64.33333333])

## 데이터 설명
- 다음은 2021년 삼성주식 데이터이다
- 시계열 학습이 가능한 형태로 변환되어있다.
- 행마다 10일치의 시작가 ,상한가 , 하한가, 종가 에 대한 행렬이 들어가 있다.

In [64]:
samsung_stock_3d = np.load("samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

(234, 10, 4)

- 한행을 보면 2차원 행렬 형태로 되어있다. 
    - 행은 일자 
    - 열은 시작가,상한가,하한가,종가 순

In [65]:
samsung_stock_3d[0] 

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000]])

## 머신러닝 모델에서 학습이 가능하게 2차원 형태로 변경해보자..


## 5.각 행의 행렬을 벡터 형태로 변환하여 데이터셋을 2차원형태로 변경해보세요.
- 출력 데이터셋의 shape -> (234,40)

```
아래 셀의 코드 작성
```

In [66]:
arr = samsung_stock_3d
newarr = arr.reshape(arr.shape[0], (arr.shape[1]*arr.shape[2]))
newarr.shape

(234, 40)

- 강사님 코드

In [67]:
samsung_stock_3d.reshape(samsung_stock_3d.shape[0],-1)

array([[81000, 84400, 80200, ..., 91800, 88000, 88000],
       [81600, 83900, 81600, ..., 87300, 84100, 85000],
       [83300, 84500, 82100, ..., 88000, 83600, 87000],
       ...,
       [78300, 78600, 77100, ..., 78300, 77500, 78100],
       [77400, 78200, 77000, ..., 79400, 78800, 79400],
       [77400, 77600, 76800, ..., 80000, 79300, 79900]])

In [68]:
import pandas as pd
import numpy as np

df = pd.DataFrame(newarr)
df

0      1      2      3      4      5      6      7      8      9   \
0    81000  84400  80200  83000  81600  83900  81600  83900  83300  84500   
1    81600  83900  81600  83900  83300  84500  82100  82200  82800  84200   
2    83300  84500  82100  82200  82800  84200  82700  82900  83300  90000   
3    82800  84200  82700  82900  83300  90000  83000  88800  90000  96800   
4    83300  90000  83000  88800  90000  96800  89500  91000  90300  91400   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
229  75100  76700  74900  76300  76100  77700  75600  77400  78300  78600   
230  76100  77700  75600  77400  78300  78600  77100  77400  77400  78200   
231  78300  78600  77100  77400  77400  78200  77000  78200  77400  77600   
232  77400  78200  77000  78200  77400  77600  76800  76900  77200  78300   
233  77400  77600  76800  76900  77200  78300  76500  76800  76500  77200   

     ...     30     31     32     33     34     35     36     37     38     39  
0    ...  89100  89700  88700  90000  88700  89700  89800  91800  88000  88000  
1    ...  88700  89700  89800  91800  88000  88000  86600  87300  84100  85000  
2    ...  88000  88000  86600  87300  84100  85000  84500  88000  83600  87000  
3    ...  84100  85000  84500  88000  83600  87000  89000  89000  86500  87200  
4    ...  83600  87000  89000  89000  86500  87200  87500  88600  86500  88100  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
229  ...  76300  77600  78500  78500  77400  77800  76800  78000  76800  78000  
230  ...  77400  77800  76800  78000  76800  78000  77600  77800  76800  77100  
231  ...  76800  78000  77600  77800  76800  77100  77900  78300  77500  78100  
232  ...  76800  77100  77900  78300  77500  78100  78900  79400  78800  79400  
233  ...  77500  78100  78900  79400  78800  79400  79800  80000  79300  79900  

[234 rows x 40 columns]

## 6.각행의 시작가 ,상한가 , 하한가, 종가별로 평균을 구해 2차원 형태로 변경해보세요.

```
아래 셀의 코드 작성
```

In [69]:
avg_raw = samsung_stock_3d.mean(axis=1) 

In [70]:
import pandas as pd
import numpy as np

df = pd.DataFrame(avg_raw)
df

0        1        2        3
0    86060.0  88820.0  85270.0  86980.0
1    86620.0  89110.0  85660.0  87180.0
2    86910.0  89520.0  85860.0  87490.0
3    87480.0  89970.0  86300.0  87990.0
4    87950.0  90410.0  86680.0  88510.0
..       ...      ...      ...      ...
229  76970.0  77840.0  76460.0  77340.0
230  77220.0  77950.0  76650.0  77420.0
231  77400.0  78010.0  76840.0  77490.0
232  77460.0  78090.0  77010.0  77690.0
233  77700.0  78270.0  77240.0  77860.0

[234 rows x 4 columns]

## 7. 5번과 6번에서 생성한 특성(열)들을 합쳐서 x_train 변수에 넣어주세요.

```
아래 셀의 코드 작성
```

In [71]:
x_train = np.concatenate([newarr,avg_raw], axis=1)
x_train

array([[81000., 84400., 80200., ..., 88820., 85270., 86980.],
       [81600., 83900., 81600., ..., 89110., 85660., 87180.],
       [83300., 84500., 82100., ..., 89520., 85860., 87490.],
       ...,
       [78300., 78600., 77100., ..., 78010., 76840., 77490.],
       [77400., 78200., 77000., ..., 78090., 77010., 77690.],
       [77400., 77600., 76800., ..., 78270., 77240., 77860.]])

- 강사님 코드

In [72]:
x_train = np.concatenate([
    samsung_stock_3d.reshape(samsung_stock_3d.shape[0],-1),
    samsung_stock_3d.mean(axis=1) 
],axis=1)
x_train

array([[81000., 84400., 80200., ..., 88820., 85270., 86980.],
       [81600., 83900., 81600., ..., 89110., 85660., 87180.],
       [83300., 84500., 82100., ..., 89520., 85860., 87490.],
       ...,
       [78300., 78600., 77100., ..., 78010., 76840., 77490.],
       [77400., 78200., 77000., ..., 78090., 77010., 77690.],
       [77400., 77600., 76800., ..., 78270., 77240., 77860.]])

In [73]:
import pandas as pd
import numpy as np

df = pd.DataFrame(x_train)
df

0        1        2        3        4        5        6        7   \
0    81000.0  84400.0  80200.0  83000.0  81600.0  83900.0  81600.0  83900.0   
1    81600.0  83900.0  81600.0  83900.0  83300.0  84500.0  82100.0  82200.0   
2    83300.0  84500.0  82100.0  82200.0  82800.0  84200.0  82700.0  82900.0   
3    82800.0  84200.0  82700.0  82900.0  83300.0  90000.0  83000.0  88800.0   
4    83300.0  90000.0  83000.0  88800.0  90000.0  96800.0  89500.0  91000.0   
..       ...      ...      ...      ...      ...      ...      ...      ...   
229  75100.0  76700.0  74900.0  76300.0  76100.0  77700.0  75600.0  77400.0   
230  76100.0  77700.0  75600.0  77400.0  78300.0  78600.0  77100.0  77400.0   
231  78300.0  78600.0  77100.0  77400.0  77400.0  78200.0  77000.0  78200.0   
232  77400.0  78200.0  77000.0  78200.0  77400.0  77600.0  76800.0  76900.0   
233  77400.0  77600.0  76800.0  76900.0  77200.0  78300.0  76500.0  76800.0   

          8        9   ...       34       35       36       37       38  \
0    83300.0  84500.0  ...  88700.0  89700.0  89800.0  91800.0  88000.0   
1    82800.0  84200.0  ...  88000.0  88000.0  86600.0  87300.0  84100.0   
2    83300.0  90000.0  ...  84100.0  85000.0  84500.0  88000.0  83600.0   
3    90000.0  96800.0  ...  83600.0  87000.0  89000.0  89000.0  86500.0   
4    90300.0  91400.0  ...  86500.0  87200.0  87500.0  88600.0  86500.0   
..       ...      ...  ...      ...      ...      ...      ...      ...   
229  78300.0  78600.0  ...  77400.0  77800.0  76800.0  78000.0  76800.0   
230  77400.0  78200.0  ...  76800.0  78000.0  77600.0  77800.0  76800.0   
231  77400.0  77600.0  ...  76800.0  77100.0  77900.0  78300.0  77500.0   
232  77200.0  78300.0  ...  77500.0  78100.0  78900.0  79400.0  78800.0   
233  76500.0  77200.0  ...  78800.0  79400.0  79800.0  80000.0  79300.0   

          39       40       41       42       43  
0    88000.0  86060.0  88820.0  85270.0  86980.0  
1    85000.0  86620.0  89110.0  85660.0  87180.0  
2    87000.0  86910.0  89520.0  85860.0  87490.0  
3    87200.0  87480.0  89970.0  86300.0  87990.0  
4    88100.0  87950.0  90410.0  86680.0  88510.0  
..       ...      ...      ...      ...      ...  
229  78000.0  76970.0  77840.0  76460.0  77340.0  
230  77100.0  77220.0  77950.0  76650.0  77420.0  
231  78100.0  77400.0  78010.0  76840.0  77490.0  
232  79400.0  77460.0  78090.0  77010.0  77690.0  
233  79900.0  77700.0  78270.0  77240.0  77860.0  

[234 rows x 44 columns]

## 8. x_train변수의 특성(열)들에 최대값과 최소값들을 구하시오.

```
아래 셀의 코드 작성
```

In [74]:
x_max = x_train.max(axis=1)
x_min = x_train.min(axis=1)
x_max, x_min

(array([96800., 96800., 96800., 96800., 96800., 96800., 91800., 91800.,
        91800., 91800., 89900., 89900., 89900., 89900., 89900., 89900.,
        89200., 87700., 86400., 86400., 86400., 86400., 86000., 86000.,
        86000., 86000., 86000., 86000., 86000., 86000., 85400., 85400.,
        85400., 85400., 85400., 85400., 85400., 85300., 85300., 84000.,
        83500., 83800., 83800., 83800., 83800., 83800., 83800., 83800.,
        83800., 83800., 83800., 83000., 85200., 86000., 86200., 86200.,
        86200., 86200., 86200., 86200., 86200., 86200., 86200., 86200.,
        86200., 85700., 84900., 84700., 84700., 84700., 84700., 84700.,
        84000., 84000., 83500., 83500., 83500., 83500., 83500., 83500.,
        83500., 83500., 83500., 83500., 83500., 83500., 83500., 82600.,
        81500., 81500., 81500., 81500., 81500., 81500., 83000., 83000.,
        83000., 83000., 83000., 83000., 83000., 83000., 83000., 83000.,
        82800., 82800., 82600., 82000., 81900., 81900., 81900., 

- 강사님 코드

In [75]:
mins, maxs = np.quantile(x_train,[0,1],axis=0)
mins , maxs

(array([68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        70040., 70550., 69510., 69920.]),
 array([90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 91800., 89100., 90600., 89800., 91800., 89100., 89700.,
        89800., 91800., 88700., 89700., 89800., 91800., 88000., 89400.,
        88520., 90410., 87060., 88510.]))

## 9.x_train변수의 특성(열)들에 분위수기준으로 5% 지점값들과 95% 지점값들을 구하시오

```
아래 셀의 코드 작성
```

In [76]:
x_min, x_max = np.quantile(x_train,[0.05,0.95],axis = 0)
x_min.shape, x_max.shape

((44,), (44,))

- 강사님 코드

In [77]:
mins , maxs = np.quantile(x_train,[0.05,0.95],axis=0)
mins.shape , maxs.shape

((44,), (44,))

## 10. 이상치를 제거해보기
- x_train변수의 특성(열)들에 분위수 기준 5% 지점의 미만값들을 5% 지점값으로 변경하고
- 95% 지점을 초과하는 값들을 95% 지점값으로 변경해보세요.

```
아래 셀의 코드 작성
```

In [78]:
quantile_05 = np.quantile(x_train,0.05)
quantile_95 = np.quantile(x_train,0.95)
idx = quantile_95 - quantile_05

minimum = quantile_05 - 1.5 * idx
maximum = quantile_95 + 1.5 * idx

arr = x_train[(minimum <= x_train) & (x_train <= maximum)]
x_train2 = arr.reshape(234,-1)
x_train2

array([[81000., 84400., 80200., ..., 88820., 85270., 86980.],
       [81600., 83900., 81600., ..., 89110., 85660., 87180.],
       [83300., 84500., 82100., ..., 89520., 85860., 87490.],
       ...,
       [78300., 78600., 77100., ..., 78010., 76840., 77490.],
       [77400., 78200., 77000., ..., 78090., 77010., 77690.],
       [77400., 77600., 76800., ..., 78270., 77240., 77860.]])

In [79]:
x_train.shape[0],x_train2.shape[0]

(234, 234)

In [80]:
np.clip(x_train, mins , maxs)

array([[81000. , 84400. , 80200. , ..., 87506. , 84803.5, 85781. ],
       [81600. , 83900. , 81600. , ..., 87506. , 84803.5, 85781. ],
       [83300. , 84500. , 82100. , ..., 87506. , 84803.5, 85781. ],
       ...,
       [78300. , 78600. , 77100. , ..., 78010. , 76840. , 77490. ],
       [77400. , 78200. , 77000. , ..., 78090. , 77010. , 77690. ],
       [77400. , 77600. , 76800. , ..., 78270. , 77240. , 77860. ]])

## 11.x_train 데이터셋에서 20%의 데이터의 인덱스들을 리스트(배열 가능)에 담아 5번 랜덤하게 반환하는 제너레이터(리스트 형태로 반환 가능) 함수를 만들어주세요
- 단, 5번 랜덤하게 반환하는 과정에서 동일한 행의 인덱스가 나오면 안된다.
    - 한번 나온 행의 인덱스는 다시 나오면 안된다는 의미
    - 모든 행의 인덱스가 한번씩은 무조건 나와야한다.
- 234행 나누기 5를 할경우 나머지가 생기기 때문에 5번째 나오는 인덱스가 담긴 리스트 혹은 배열의 크기는 앞서 나온 크기와 차이가 나도 된다.  
- 제너레이터가 어려우신 분들은 그냥 인덱스들을 담고 있는 리스트(배열)들을 리스트에 담아서 return 하셔도 됩니다.

```
아래 셀의 코드 작성하여 함수 구현
```

### yield를 이용한 방식

In [81]:
def split_dataset(dataset):
    # 나중에 파라미터로 받을수도 있으니 지역변수 선언
    n_split = 5
    seed = 42

    n_row = len(dataset) # 총 개수
    index_arr = np.arange(n_row) # 인덱스

    np.random.seed(seed)
    np.random.shuffle(index_arr) # 랜덤하게 뽑기위해 섞기
    n_samples = n_row // n_split 
    for i in range(n_split): 
        start = i*n_samples
        end = start + n_samples  
        if i+1 == n_split: 
            end =  n_row 
        yield index_arr[start:end] 

- 다음 셀은 위에 함수 실행 결과를 검증하는 부분

In [82]:
index_list = split_dataset(x_train)
lst = [] # 중복 인덱스가 있는지 확인하기 위한 리스트
for idx in index_list:
    print(idx)  # 리스트 내용 확인
    lst.extend(idx) # 중복 인덱스가 있는지 확인하기 위해 리스트에 담기
len(set(lst)) # 중복 제거후 크기가 데이터셋 크기와 같다면 성공!! 즉 234개면 성공!!

[ 69 206 180   9 127 109 196  93 213  15 224  55 227  30 201 147  19 112
 225  24 208  10  95 144 220  25  86 183  84  18 146  66  45 139 125 170
 164  16 156 177 161 203 124  60 199 229]
[ 82 117 155 148 158 231 162 218 108  97 168  73  38 104 172 171 111 221
  67 217 113  68  75  29 114 126  79   5  56 120 141 152  65 135 198 138
  31  12  35  28  42  96 119 209  51 184]
[185  76  41 101 142  78 137  26 153 192 186   0   2  77  46 100 115 140
 167  90  85 165 154  98  36 136  61  22 118 215 132  33  11 228 182   6
  27 143   4 122  32 181  62 128 223 175]
[ 70 178  64  44 150  40 123  23 173 197  81  39 195  47  94 176  43 145
 159   3 105  53 133 211 232 216  49 163  80  34   7 110  91  83 207 212
  89   8  13  59 200 131  17 166  72 204]
[134 190 222  63  54 107  50 193 174 194 189 230 205 169  58  48  88  21
  57 160 226 187 191 129  37 157 219   1  52 149 130 151 103  99 116  87
 202  74 214 210 121 233  20 188  71 106  14  92 179 102]


234

### yield from을 이용한 방식

In [83]:
def split_dataset(dataset):
    # 나중에 파라미터로 받을수도 있으니 지역변수 선언
    n_split = 5
    seed = 42

    n_row = len(dataset) # 총 개수
    index_arr = np.arange(n_row) # 인덱스

    np.random.seed(seed)  
    np.random.shuffle(index_arr) # 랜덤하게 뽑기위해 섞기
    n_samples = n_row // n_split # 20% 의 데이터셋 개수
    n_sub = n_row - n_samples * n_split 
    index_list = index_arr[:n_row-n_sub].reshape(n_split,-1).tolist()

    if n_sub > 0: # 남는개수가 있다면..
        index_list[-1].extend(list(index_arr[n_row-n_sub:])) # 마지막 인덱스 리스트에 추가 확장
    yield from index_list 

In [84]:
index_list = split_dataset(x_train)
lst = [] # 중복 인덱스가 있는지 확인하기 위한 리스트
for idx in index_list:
    print(idx)  # 리스트 내용 확인
    lst.extend(idx) # 중복 인덱스가 있는지 확인하기 위해 리스트에 담기
len(set(lst)) # 중복 제거후 크기가 데이터셋 크기와 같다면 성공!! 즉 234개면 성공!!

[69, 206, 180, 9, 127, 109, 196, 93, 213, 15, 224, 55, 227, 30, 201, 147, 19, 112, 225, 24, 208, 10, 95, 144, 220, 25, 86, 183, 84, 18, 146, 66, 45, 139, 125, 170, 164, 16, 156, 177, 161, 203, 124, 60, 199, 229]
[82, 117, 155, 148, 158, 231, 162, 218, 108, 97, 168, 73, 38, 104, 172, 171, 111, 221, 67, 217, 113, 68, 75, 29, 114, 126, 79, 5, 56, 120, 141, 152, 65, 135, 198, 138, 31, 12, 35, 28, 42, 96, 119, 209, 51, 184]
[185, 76, 41, 101, 142, 78, 137, 26, 153, 192, 186, 0, 2, 77, 46, 100, 115, 140, 167, 90, 85, 165, 154, 98, 36, 136, 61, 22, 118, 215, 132, 33, 11, 228, 182, 6, 27, 143, 4, 122, 32, 181, 62, 128, 223, 175]
[70, 178, 64, 44, 150, 40, 123, 23, 173, 197, 81, 39, 195, 47, 94, 176, 43, 145, 159, 3, 105, 53, 133, 211, 232, 216, 49, 163, 80, 34, 7, 110, 91, 83, 207, 212, 89, 8, 13, 59, 200, 131, 17, 166, 72, 204]
[134, 190, 222, 63, 54, 107, 50, 193, 174, 194, 189, 230, 205, 169, 58, 48, 88, 21, 57, 160, 226, 187, 191, 129, 37, 157, 219, 1, 52, 149, 130, 151, 103, 99, 116, 87, 

234

## 12.시계열 학습데이터 만들기
- 다음의 데이터는 2021년도 삼성 주식 데이터이다.
- 열부분은 시작가 ,상한가 , 하한가, 종가 순으로 되어있다.
- 행은 2021년도 거래 일자이다.

In [85]:
samsung_stock = np.load("samsung_stock_2021.npy")
samsung_stock.shape

(248, 4)

In [86]:
samsung_stock[-5:] # 뒤에 5행만 확인해보자

array([[80200, 80800, 80200, 80500],
       [80600, 80600, 79800, 80200],
       [80200, 80400, 79700, 80300],
       [80200, 80200, 78500, 78800],
       [78900, 79500, 78100, 78300]])

### 시계열 학습데이터로 변환하는 함수를 만드시오.
- samsung_stock 변수의 데이터는 2차원 데이터이다.
- 학습데이터는 행별로 10일치의 행과 4열(시작가 ,상한가 , 하한가, 종가) 형태의 행렬을 담고 있는 3차원 형태의 데이터셋으로 변경하시오.
- 정답데이터는 미래의 5일치의 종가를 예측해야 한다는 가정하에 행별로 미래의 5일치의 종가가 담긴 2차원 형태의 데이터셋으로 변경하시오. 
- 1일씩 이동하면서 데이터셋을 구성하시오.

```
아래 셀의 코드 작성하여 함수 구현
```

In [87]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    x_train = []
    y_train = []
    for i in range(seq_len,samsung_stock.shape[0] + 1  - pred_len): #  마지막 하나가 빠짐... 1 더해주기
        x = samsung_stock[i-seq_len:i] 
        y = samsung_stock[i:i+pred_len,3] 
        x_train.append(x)
        y_train.append(y)

    x_train = np.array(x_train)
    y_train = np.array(y_train)

    return x_train , y_train

- 다음 셀들은 위에 함수 실행 결과를 검증하는 부분

In [88]:
x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

((234, 10, 4), (234, 5))

In [89]:
x_samsung_stock = np.load("samsung_stock_2021_3d.npy")
y_samsung_stock = np.load("y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!

(True, True)

### 강사님 코드

In [92]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    window_size = seq_len + pred_len
    window_arr = [
        samsung_stock[i-window_size:i]
        for i in range(window_size ,samsung_stock.shape[0] + 1) #  마지막 하나가 빠짐... 1 더해주기
    ]

    window_arr = np.array(window_arr)
    x_train = window_arr[:,:seq_len]
    y_train = window_arr[:,seq_len:,3]

    return x_train , y_train


x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

((234, 10, 4), (234, 5))

In [91]:
x_samsung_stock = np.load("samsung_stock_2021_3d.npy")
y_samsung_stock = np.load("y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!

(True, True)

- 위에 두개의 예시 모두 데이터가 수만건 혹은 수십만건일 경우 수십만 , 수만의 반복을 통해 데이터가 만들어진다.
- 시계열 학습데이터로 변환과정에서 몇분에서 몇십분의 시간소요가 발생한다.
- 개발자의 기본소양중에 하나로 코드실행이 오래 걸리는걸 극도로 싫어해야한다.
- 데이터가 수만건이 있던 수십만건이 있던 동일하게 시계열 데이터로 변환을 수초내로 할수있다.

